---
# handlers file for ansible_role_microk8s

- name: Refresh certs
  become: yes
  command: microk8s refresh-certs

- handlers:
  - name: Restart MicroK8s
    become: yes
    command: microk8s stop && microk8s start
